name: Run Cloudflare Pages Preview on Fork PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Verify PR is from a fork
        run: |
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.repository }}" ]]; then
            echo "PR is not from a fork. Skipping deployment."
            exit 0
          fi

      - id: deploy
        if: success()
        uses: tomjschuster/cloudflare-pages-deploy-action@v0.0.12
        with:
          account-id: '${{ env.CF_ACCOUNT_ID }}'
          project-name: '${{ env.PAGES_PROJECT_NAME }}'
          api-key: '${{ secrets.CF_GLOBAL_APIKEY }}'
          email: '${{ secrets.CF_EMAIL }}'
          preview: true
          production: false
          github-token: '${{ secrets.GITHUB_TOKEN }}'
        env:
          CF_ACCOUNT_ID: eb09a67d16effcedf18472e3926ce09d
          PAGES_PROJECT_NAME: shs
          