name: Run Cloudflare Pages Preview on Fork PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Verify PR is from a fork
        run: |
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.repository }}" ]]; then
            echo "PR is not from a fork. Skipping deployment."
            exit 0
          fi

      - id: deploy
        if: success()
        uses: tomjschuster/cloudflare-pages-deploy-action@v0.0.12
        with:
          account-id: '${{ env.CF_ACCOUNT_ID }}'
          project-name: '${{ env.PAGES_PROJECT_NAME }}'
          api-key: '${{ secrets.CF_GLOBAL_APIKEY }}'
          email: '${{ secrets.CF_EMAIL }}'
          preview: true
        env:
          CF_ACCOUNT_ID: eb09a67d16effcedf18472e3926ce09d
          PAGES_PROJECT_NAME: shs
          
      - if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const deploymentUrl = '${{ steps.deploy.outputs.deployment-url }}';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Your deployment preview is available at: ${deploymentUrl}`
            })
